$ErrorActionPreference = "Stop"

$repositoryRoot = Split-Path -Parent $PSScriptRoot
$sourceRoot = Join-Path $repositoryRoot "src/Mvx.ApiClient.Net"
$abstractionsRoot = Join-Path $sourceRoot "Abstractions"
$clientsRoot = Join-Path $sourceRoot "Clients"

$domains = @(
    "Account",
    "Application",
    "Block",
    "Collection",
    "DappConfig",
    "Delegation",
    "Event",
    "HealthCheck",
    "Identity",
    "Key",
    "Marketplace",
    "Miniblock",
    "Network",
    "Nft",
    "Node",
    "Pool",
    "Provider",
    "Result",
    "Round",
    "Shard",
    "Stake",
    "Tag",
    "Token",
    "Transaction",
    "TransactionBatch",
    "Transfer",
    "Username",
    "WaitingList",
    "Websocket",
    "XExchange"
)

$missing = foreach ($domain in $domains) {
    $interface = Join-Path $abstractionsRoot "I$($domain)Client.cs"
    $implementation = Join-Path $clientsRoot "$($domain)Client.cs"
    if (-not (Test-Path -LiteralPath $interface)) {
        $interface
    }
    if (-not (Test-Path -LiteralPath $implementation)) {
        $implementation
    }
}

if ($missing) {
    throw "Missing handwritten domain client files:`n$($missing -join "`n")"
}

$generatedDirectory = Join-Path $sourceRoot "Generated"
if (Test-Path -LiteralPath $generatedDirectory) {
    throw "Production generated-source directory must not exist: $generatedDirectory"
}

$generatedSources = Get-ChildItem -LiteralPath $sourceRoot -Recurse -File -Filter "*.g.cs" |
    Where-Object { $_.FullName -notmatch '[\\/](bin|obj)[\\/]' }
if ($generatedSources) {
    throw "Production generated C# sources are not allowed:`n$($generatedSources.FullName -join "`n")"
}

$sourceFiles = Get-ChildItem -LiteralPath $sourceRoot -Recurse -File -Filter "*.cs" |
    Where-Object { $_.FullName -notmatch '[\\/](bin|obj)[\\/]' }
$generatedMarkers = $sourceFiles | Select-String -SimpleMatch "<auto-generated"
if ($generatedMarkers) {
    throw "Production source contains auto-generated markers:`n$($generatedMarkers.Path -join "`n")"
}

$operationCount = @(
    Get-ChildItem -LiteralPath $clientsRoot -File -Filter "*Client.cs" |
        Select-String -Pattern '^\s*\[ApiOperation\('
).Count
if ($operationCount -ne 157) {
    throw "Expected 157 handwritten ApiOperation mappings, found $operationCount."
}

Write-Host "Handwritten GET surface verified: $($domains.Count) domain client pairs and $operationCount operation mappings."
